### PR TITLE
do not use index as a key

### PR DESCRIPTION
**Pull request by TymchenkoOleksandr**
[Index as a key is an anti-pattern](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318)

### CODE REVIEW

**Comment by DmitryMasley** [comment]
We really need this change for our project.

**Comment by BrianGenisio** [comment]
Thanks for the ping.

What if `value` is not a scalar?  Don't keys need to be scalars?

**Comment by BrianGenisio** [comment]
Yeah, `value` is an opaque `any` type and `key` is a string.  If `value` were a number, object, etc, we'd have a problem.

It seems like `Option` can have an optional `key` property and we'll use that if it exists, and `index` if not too aid in backwards compatibility?

What do you think of that proposal @TymchenkoOleksandr ?

**Comment by TymchenkoOleksandr** [comment]
@BrianGenisio , completely agree, please check once more

**Comment by TymchenkoOleksandr** [comment]
thanks a lot

**Comment by BrianGenisio** [comment]
No problem!  Sorry I didn't see this in the first place and thanks for the tag.

I've published this to @khanacademy/react-multi-select@0.2.8

**Pull request merged**
