### PR TITLE
Add SelectPanel & SelectItem to named exports

### PR DESCRIPTION
**Pull request by kevgathuku**
Hello there 👋
I found that in some instances I would like to use the SelectPanel & SelectItem components.

This PR exports SelectPanel & SelectItem as named exports

Cc @daisymacharia

### CODE REVIEW

**Comment by BrianGenisio** [comment]
Just for my own understanding, when would it be useful to have these components exported?

**Comment by BrianGenisio** [comment]
Published 0.3.3

**Comment by kevgathuku** [comment]
Hi @BrianGenisio thanks for merging this 🙂
In our codebase, we wanted to use the multi-select without the search field

**Comment by BrianGenisio** [comment]
@kevgathuku Ah!  For that, you can just use the `disableSearch={true}` in the component.

**Comment by kevgathuku** [comment]
> @kevgathuku Ah! For that, you can just use the `disableSearch={true}` in the component.

Thanks @BrianGenisio 	
There must be something else I'm forgetting, but thanks for the merge!

**Pull request merged**
