### PR TITLE
export SelectPanel

### PR DESCRIPTION
**Pull request by TymchenkoOleksandr**

### CODE REVIEW

**Comment by TymchenkoOleksandr** [comment]
@BrianGenisio, take a look, please

**Comment by BrianGenisio** [comment]
This seems simple enough.  I'm going to merge it in... but can you update in the description why this change is desired, please?

**Comment by TymchenkoOleksandr** [comment]
thanks, @BrianGenisio. Could you publish new version, please?

**Comment by BrianGenisio** [comment]
Published 0.3.3

**Pull request merged**
